### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by LoicBrassart** [LoicBrassart/suivi-candidatures#2]
1. **En tant que**: Visiteur
2. **Je veux**: Accéder à la homepage
3. **Afin de**: Voir une présentation sommaire du site

- **Priorité**: 80
- **Estimation**: 5
- **Description**: Il nous faut une homepage (responsiive)

**Todo Frontend**:

- [ ] Initialiser un frontend
- [ ] Nettoyer le contenu par défaut
- [ ] Initialiser les outils (styled-components, etc)
- [ ] Préparer un contenu statique

**Todo Backend**:

- [x] RaS
